# Generated by Django 5.1 on 2024-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='industry_identifiers',
            field=models.JSONField(default=list),
        ),
    ]
